using AutoMapper;
using MaverickBank.DTOs.Account;
using MaverickBank.DTOs.Beneficiary;
using MaverickBank.DTOs.Branch;
using MaverickBank.DTOs.Loan;
using MaverickBank.DTOs.Transaction;
using MaverickBank.DTOs.User;

namespace MaverickBank.MappingProfile
{
    public class AutoMapperProfile : Profile
    {
        public AutoMapperProfile()
        {
            CreateMap<Models.Branch, BranchResponseDto>();
            CreateMap<CreateBranchDto, Models.Branch>()
                .ForMember(dest => dest.BranchId, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore());

            CreateMap<Models.User, UserResponseDto>();
            CreateMap<CreateUserDto, Models.User>()
                .ForMember(dest => dest.UserId, opt => opt.Ignore())
                .ForMember(dest => dest.PasswordHash, opt => opt.Ignore())   
                .ForMember(dest => dest.IsActive, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore());
            CreateMap<UpdateUserDto, Models.User>()
                .ForMember(dest => dest.UserId, opt => opt.Ignore())
                .ForMember(dest => dest.RoleId, opt => opt.Ignore())
                .ForMember(dest => dest.Email, opt => opt.Ignore())
                .ForMember(dest => dest.PasswordHash, opt => opt.Ignore())
                .ForMember(dest => dest.Gender, opt => opt.Ignore())
                .ForMember(dest => dest.DateOfBirth, opt => opt.Ignore())
                .ForMember(dest => dest.AadhaarNumber, opt => opt.Ignore())
                .ForMember(dest => dest.PANNumber, opt => opt.Ignore())
                .ForMember(dest => dest.IsActive, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore());

            CreateMap<Models.Account, AccountResponseDto>();
            CreateMap<CreateAccountDto, Models.Account>()
                .ForMember(dest => dest.AccountId, opt => opt.Ignore())
                .ForMember(dest => dest.AccountNumber, opt => opt.Ignore())  // generated by service
                .ForMember(dest => dest.Balance, opt => opt.MapFrom(src => src.InitialDeposit))
                .ForMember(dest => dest.Status, opt => opt.Ignore())
                .ForMember(dest => dest.OpenedDate, opt => opt.Ignore())
                .ForMember(dest => dest.ClosedDate, opt => opt.Ignore());

            CreateMap<Models.Beneficiary, BeneficiaryResponseDto>();
            CreateMap<AddBeneficiaryDto, Models.Beneficiary>()
                .ForMember(dest => dest.BeneficiaryId, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore());

            CreateMap<Models.Transaction, TransactionResponseDto>();

            CreateMap<Models.Loan, LoanResponseDto>();
            CreateMap<Models.LoanApplication, LoanResponseDto>()
                .ForMember(dest => dest.LoanId, opt => opt.MapFrom(_ => 0L))
                .ForMember(dest => dest.AccountId, opt => opt.MapFrom(_ => 0L))
                .ForMember(dest => dest.ApprovedAmount, opt => opt.MapFrom(_ => 0m))
                .ForMember(dest => dest.InterestRate, opt => opt.MapFrom(_ => 0m))
                .ForMember(dest => dest.EMIAmount, opt => opt.MapFrom(_ => 0m))
                .ForMember(dest => dest.OutstandingAmount, opt => opt.MapFrom(_ => 0m))
                .ForMember(dest => dest.StartDate, opt => opt.MapFrom(_ => DateTime.MinValue))
                .ForMember(dest => dest.EndDate, opt => opt.MapFrom(_ => DateTime.MinValue))
                .ForMember(dest => dest.LoanStatus, opt => opt.MapFrom(src => src.ApplicationStatus));
            CreateMap<ApplyLoanDto, Models.LoanApplication>()
                .ForMember(dest => dest.LoanApplicationId, opt => opt.Ignore())
                .ForMember(dest => dest.ApplicationStatus, opt => opt.Ignore())
                .ForMember(dest => dest.AppliedDate, opt => opt.Ignore())
                .ForMember(dest => dest.ReviewedBy, opt => opt.Ignore())
                .ForMember(dest => dest.ReviewedDate, opt => opt.Ignore())
                .ForMember(dest => dest.Remarks, opt => opt.Ignore());
        }
    }
}
